apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-grafana
  namespace: grafana
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: grafana-cnpg-main
  podMetricsEndpoints:
  - port: metrics