apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-internal
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/networking/traefik-internal/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

