apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WyuN0MU7OYDrUQA/tzrffUWFkDoqGm13FCMR27qZ8cY3Sd97FLFvoSU+6AajuxKhzDJFwvJsjbDCBNTbAvPzOlx9FTi1JGrvuyifuN5giUoHyqgxxAKgVQDg2/c1/c4lDJhew6isXdLc1GSZIOKR4y1kBEYCLRr1Nxf0DsyXIIjlmXKQ8NQHnJKPG0KFlks9ksfKF32jUVBQgcdhwD/yH2NUTzbQClLYot80qio0QhLeNd3V9NSfWcaIX/wxFsozNIc+qmnV8q4E2fF3kyESdw5jUbY5Unqz/26DiIaiNRu1P/26c1XEqdz0vmGt1PrQ7NtBD9M+22y7Dl4cQik1yWo55XQkZwsJJOg5gNLT1JdVLHCop30TNi5FyH/4rSq1,iv:kZK5X8rRAEb5zeMHu428JHDiSV0L68VEGtFUdujQnsc=,tag:5WAfl1BX1OqAT7f+e3Lkfg==,type:str]
    identity.pub: ENC[AES256_GCM,data:5WiFpGE08J9GrPGJEvMoS+inFlGRWBqxcvkBhRTup7UukI6U5UrJFaqeNCyNuP3Yy2AnZIQo74rPpl0h4061Mswhe71ojNxmdSfnaAn9jAKEEa7fVl0ra3HquX6hEQ1hYTCBfknEw/hJJ/rkwGtgogR8H8bomZdi6xiswWCsm51nHQouA6peuvoXtlnIx5sHh+fMViuS3o/3wBl2XnLtR1wiDFI34exC4jfiFRVtwOGVqPXU+iKc8qRmmkS0ttifPddOxa8vz+Jns9CGWg==,iv:/sMIksbWwT4XkmUy3QoIY+40qtQJsi+NwgoQo3w+qQc=,tag:WudJxAqHUT/YNh33j7Uj7Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:w6HDhjgbhl3b+gjyndGTrvhNa1JC566b7JHIg1VUnhTP1ElykLOKsfyd6hbaTcQL1HS0QaiIQ+RL+cCjne8rQYhynl9GNKxZ8hre53PFPqy3zW8BAySTLsha5dxUXAz4+OfOhSAFlI2wE1FnH5eEZMTnQreYz2z+E9qvACWjR5Cj77Lsx1sZO3wT/AeJbEV5w5/k0gb1YsW/r9LXHB46QbaWsFhH9xW+yWtl,iv:jeTDM8hnbDuEZnWOEeYAjA2nl4YmmafKaAG/OPjH/D0=,tag:J1BAq28X6/sHSq7i2EurLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uaud96tmvkrmct5ssh20a4dwqy825ru5tqsdp8hu3syxlp4p9glqkamlya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdy9peFgrOVNzdnpwNnZl
            YlNHTkd6SmtMWVd3S2RFenpKaUxBdmpESFIwCnBOc2tZY3Vub0VtaG9oenBpa3Ry
            WlJxeFR3RkFTeS8yUDBDM3FJSm5aUXcKLS0tIFg0TVlmTjJEMjZ1QVVvVGp6SktP
            cHZFVTdycVZpdnBmVGJya2hJRzhMUjQK3x7R0V00xjfPhP4UrJVvE4HR8Y9nBLUQ
            M7PLUJtO1QKMNVFIXM5OrH3bir53KE3lEhc/t/2zBuhs5TNgYwOj1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T13:59:57Z"
    mac: ENC[AES256_GCM,data:OEY0rp1RA1+9ZRMAjLQVW3NZRl/KlBLiRbN1GiV2oM/b9cdtKD6EPVzEz7IeybHYvKP1fEW2Os/Y9lbJsJ43brNNFnQpPU/0+tgrfcMGtDStmtW2pjz8L/nJVw+NHGCKadYPnRTjr0YVqhqQx4JlKfTJoWUjgvwP3iYNLrUgYz0=,iv:gEqtH4ruEcGKshlLmbjLUarHlYJfzTnnWp2fd7ZsibY=,tag:EaGUmNLyyKugAMsWFHqWrw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
