apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4HdSuPUnsv84mguyEL1WsshSCvY52x6R3PxjtkaON9iN45a5T/wy5F1f1JLIg6kKp/sKQ3VtjP8ZuJTm1qdAzF9++KwqT5xrv7unUijNAhQNCkyJmr9+5acM+dc2vftPhb/CO4hwJuiM0juwI9JxbD6bDsQq/NQBaCz/u4n2/3a/ZkcGwOvlTlJuTcDCjtYUMW+O0pybLZg+knhGps2r0tFQw0VgY3ZUXKwcT0Y3goNcgXh4u3hc/eCxEGuzvekaq6rbD8hlBjASMMP8kgj9QnKW3IM6Asl2Sr2Wk783H04mXZHLpxyzIjBnHGOvf4TEBy7ehnvlwgupI87+hbI29azauEfC7fj0FTf6tlQgGu0kY318+5D0Pc8O+aSciXBO,iv:anCXBqNvjvTiPClkJaaefDa8b2oG9GOZsiom0hWo4nw=,tag:bC53nucgs0G7UpBVVaGFDw==,type:str]
    identity.pub: ENC[AES256_GCM,data:AcnqXu60i+KEdaJ35djfRMLpZVU0QvcrivndphxLHUzUxUeGg1Qk7yXqiGUnZfftBhWzuma2rtiDq3M2Vzekc07CN7RgUeWryPBIjPBZfaWGeFvb1MlFF5NQCgJOLeEIbzM3yNnJP6XC3X5U+Eo3UA61EibAPDpEyAvNPpRychZrU3Wpb9LPNIusLpqjB71GNt/dkS3TgW3+BTrCi7NHiKSFyouzoO0/5m/mlnx++jg47DgcseYYV0pwZBjcSKT496Pj+XkSTS0c7YhLvg==,iv:f9MdhX6vIe6K+Rv2PpIjXUI4KpYUsfhyvspkFJN0KiQ=,tag:DxeXREd7QrZc6A1IB59PlA==,type:str]
    known_hosts: ENC[AES256_GCM,data:hv/jAdf8RgCc4yFSw8GZAu6AvhRum9g9DK40Klqsoaahu1XIuduVnYSvIu3YBJeJVBEYRxN4ziNn0ZoBhCwlNGkQc19mDaF+6qXm4l5QxqnPaLVAYTuvzGaVwckKf9Kg0sw5qKDQmG3YIGtxyWG/IyfJax3Fya2lpWsJS7cUNOw1gAhMX8d2iLXtP6c1Yyag3oHx+wLL4LhwsXYQyft80xmYElqLpJsDd+48,iv:MBObnxOetGrr80gA/s/gy7+f/gGH404tvteM8JQX6FU=,tag:jcRGtJTgWaltce2gcpU56Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uaud96tmvkrmct5ssh20a4dwqy825ru5tqsdp8hu3syxlp4p9glqkamlya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZR01aV2Q4UjAzMkcwTVJP
            TXZDL0JxelgwZ0t3ZlZrZjRxTDhpeXh5aDJVCkh2NkgxbWpqOEFPbGo1SzRtSkx1
            ZzRkM0VFUGtyWk5HNVFTd1VWMDBwWjgKLS0tIDF4UldDWXR4dlFzOFExRjE3cUZw
            VVl5aDlFaEZBcXIxV3gxOThab2RUS3MKK9x7RA+8wlLNRmkVqEjiBr4xvoqLJy9E
            VlveUbymCuLHySgLZiTqsXkLbVAJ4KX8ttCZi1xoEtN5QwXSfabPVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T12:23:41Z"
    mac: ENC[AES256_GCM,data:onD5SQ6DX8hDDW+KM8htEpPKf8DHVI19u/YPX/2qMBqiDnMV3YE7qCthNdrnjWWgPMrx+kMFEDhZBLlqqFs6kb34cWTuFVa0L9evP6nmgnVLagv4DRj8UnlL4QSLB7eO7D9Iclyevda+KHDosxCI+AvAspk/eS/w9GD5lV6ncFk=,iv:vXUP7+fuB+IPfkHH676QZoVyl2mO0WuxlJHWfFW/Eh8=,tag:FUQo0fMzHm2gdmoLc8iVSw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
