apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DcIEOMq4j+cv25S8ZyNOSp1l7YAdfxMu9hoz5c4VGphIFx8Ut+pIXuzzm7KnF3dIEWpJ5Al49K6EHgTjIHGDKewjAk7KQa5WzUT/qzVBreZSPBs2wsWvYdT1iW8T+bY953Dr0MBpHdTq0QlnpDvgfSs04iuPZXiBssOEy/T9+mz8+Lbo1yPFd2y5UsKmQGTsRxsQzIWOJV6Cl4pt52zDp0KfhZMHwFoQ3Diuz/vLco2eUFEaxJhXbGXG3rQKRP7OABm9WyMTGFwBtHXbbQpKg1CPJIWfc0wVrMFXXmIsTcvwoK8zSjeN1MpzaTyb8/wg8EmDoI9raCaKdejjvmfSKMNlTeE3uHyygnOvmbu8dNV5a//rM02Cs6RLIwn1Xsjg,iv:0+wJ39oVaHAuqV28B/LKQsi8xz2js6U5CHSWKSQ48FY=,tag:zXwMx6O/29gWEsn3S6NlXw==,type:str]
    identity.pub: ENC[AES256_GCM,data:yopPexKBMKzjB8a1ai5f06EsSr4l5urBj1HCgRQTtHw4YPD2EEv/J0eBoX5tV8nuheujRiCmVnjfZ6isgKycAOIJGKcixxFGccpxZgqcP34i+qKAsi1oMsz1jE6ef1li2F8Ev+oElmc/F/FGX5MnjUL/Gvn/rUjio15o9JfVkpu+lkYYCobcssxCvmL0vJbZu66cnNT+XKTsMCgG5V76ha3k8bo31Ci906nGvOBhS0KZSFqmWZXoKUqmT52TVtQNejdGmEqqwJGX+3Ojgg==,iv:BrbQ9mR129w0sGeqKX7TcUzu7t2Ae1q7ZJFhlbd7Cc0=,tag:3fcvsHXv+iV7HndM7zOieA==,type:str]
    known_hosts: ENC[AES256_GCM,data:v7hFCtKn+mpb3KveFCYDN1NTh0B9hKvZxpslOw53+a5kbwTHrnbZswZUocv5QKGEWz5Q/9lKUYRXzGJffP3/g0Pk9Ed0lFgNu03bR/blKSTvEYzr0QdungiqXZ9jn3QOUlrGwDb4jDzHXsHP74eeBukc9qA54NnrmfA36cGVLgzZczKggcOWYIInhOYx2R3R+DwbRU8BFuHy4Nh4P6W3UI1PLfB2u8IhadxJ,iv:e4KRGW8/dk3NMu48bnx/YZs8n+Bzg168E26LZD3ksC4=,tag:8TDunmw1tr6fUZtLRiTt1g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1uaud96tmvkrmct5ssh20a4dwqy825ru5tqsdp8hu3syxlp4p9glqkamlya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMDg5Ly94ckVVYUxUaWhO
            RHFMTkdnNHkzSzBsc3krZTBkdld0Z0IxZ1VrCjlsRm5FcWw1ZUZveGpHaGl1MzEw
            OHludTczTFBOTXN5TjdKSjI1OTJRemMKLS0tIEQwTnZYMkorblhJbHQzMWpBOFAw
            TVQxYUp3SkhCRlgvOFpLRnhMRW9DNGsKsiBrRdwjKWpXWKU7b2JfLaZxHzPTCINk
            i5KGniy0CNo0JIENy4bqD0qGoTivLiMtfomkdb8maCEMsRD+vRQImQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T11:01:35Z"
    mac: ENC[AES256_GCM,data:OziTuiAeqdGF6KDjhpiLgQai8QmoB1lKSVANHlPZUaitS3D3oSwXGN7DdckJVhfSLWAE8+a/5U0l9QmIyA34jiX4F5MYkCy+Kk6oQusQxyfh5LSSZgBeewspZGs8H3jV1D/eSAwvD+l3OOpUHQeI1eQXkO7WRIba3CfWdLjR0Ok=,iv:9m4WWf7F0GwawRCDKLCd+YGl7iGaSekGX4nYoC/1Gis=,tag:d0MJBbF8ljpQqVeJP50r2Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
