apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
secretGenerator:
  - name: authelia-config
    namespace: authelia
    files:
      - authelia-config.yaml
configurations:
  - kustomizeconfig.yaml