---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: traefik-internal
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 39.0.5
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # https://artifacthub.io/packages/helm/traefik/traefik?modal=values
    deployment:
      enabled: true
      replicas: 2
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.io/ip-allocated-from-pool: main
        metallb.io/loadBalancerIPs: ${TRAEFIK_INTERNAL_IP}
      spec:
        externalTrafficPolicy: Local
    logs:
      general:
        level: INFO
      access:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesGateway:
        # -- Enable Traefik Gateway provider for Gateway API
        enabled: true
    # tlsStore: 
    #   default:
    #     defaultCertificate:
    #     secretName: "${SECRET_PUBLIC_DOMAIN/./-}-tls"
    ports:
      web:
        http:
          redirections:
            entryPoint: 
              to: websecure
              scheme: https
              permanent: true
      websecure:
        http:
          tls:
            enabled: true
            options: "default"
    ingressRoute:
      dashboard:
        enabled: true
    metrics:
      ## Prometheus is enabled by default.
      ## It can be disabled by setting "prometheus: null"
      prometheus:
        service:
          # -- Create a dedicated metrics service to use with ServiceMonitor
          enabled: true
        # -- When set to true, it won't check if Prometheus Operator CRDs are deployed
        serviceMonitor:
          # -- Enable optional CR for Prometheus Operator. See EXAMPLES.md for more details.
          enabled: true
